/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_example_jnitt_HelloNative */

#ifndef _Included_com_example_jnitt_HelloNative
#define _Included_com_example_jnitt_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnitt_HelloNative
 * Method:    fun1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jnitt_HelloNative_fun1
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jnitt_HelloNative
 * Method:    fun2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnitt_HelloNative_fun2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_jnitt_HelloNative
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_jnitt_HelloNative_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
